Implementing OpenAPI spec
navikt/soknadsmottaker pull request #48
Opened 2022-02-08 17:20 UTC by sjoblomjsqueed

Implementing OpenAPI endpoint. Updating tests. Removing old code and tests.

2022-02-08 17:21 UTC, sjoblomjsqueed commented on mottaker/src/main/kotlin/no/nav/soknad/arkivering/soknadsmottaker/rest/Receiver.kt
> +fun convertToSoknad(request: SoknadInnsendtDto) =
This class will be removed once nobody uses the old endpoint any more

2022-02-14 11:38 UTC, sjoblomjsqueed commented on mottaker/src/main/kotlin/no/nav/soknad/arkivering/soknadsmottaker/service/Converter.kt
> +		"ORIGINAL"
> Se på dette eksempelet på en søknad mottatt av søknadsmottaker: `SoknadInnsendtDto(innsendingsId=10019U2i9, ettersendelse=false, personId=***, tema=TSO, innsendtDato=2022-01-24T08:51:57, innsendteDokumenter=[InnsendtDokumentDto(skjemaNummer=NAV 11-12.10, erHovedSkjema=true, tittel=Kjøreliste for godkjent bruk av egen bil, varianter=[InnsendtVariantDto(uuid=af99da5f-1f4a-48b3-b631-2226d2abbb9c, mimeType=application/pdf, filNavn=NAV 11-12.10.pdfa, filStorrelse=22196, variantformat=ARKIV, filtype=PDF/A), InnsendtVariantDto(uuid=b354b025-7f06-4dd9-9d63-eea47f73a674, mimeType=application/xml, filNavn=RefusjonDagligreise.xml, filStorrelse=975, variantformat=ORIGINAL, filtype=XML)]), InnsendtDokumentDto(skjemaNummer=L7, erHovedSkjema=false, tittel=Kvitteringsside for dokumentinnsending, varianter=[InnsendtVariantDto(uuid=ff4365ea-15a0-4dcc-9e37-2978ed9e13d2, mimeType=application/pdf, filNavn=L7, filStorrelse=42303, variantformat=ARKIV, filtype=PDF)])])` Det er 2 varianter av hoveddokumentet, en PDF -> ARKIV og en application/xml -> ORIGINAL. Det er feil at erHovedskjema alltid er ARKIV.

Bra funn. Hvordan mener du at logikken skal være?

2022-02-14 11:43 UTC, nils-arne commented on mottaker/src/test/kotlin/no/nav/soknad/arkivering/soknadsmottaker/service/ConverterTests.kt
> +		val result0 = convert(soknad)
Ref kommentar til setting av arkivformat. Det må vel gjøres en justering her.

2022-02-14 11:46 UTC, nils-arne requested changes
Sjekk kommentar relatert til setting av arkivfomat.
Har editert soknadsmottaker-api.yml i innsending-api for generering av HealthAPI, burde du ikke ha lagt til generering av apiet for ping/isAlive/isReady?

2022-02-14 12:14 UTC, nils-arne commented on mottaker/src/main/kotlin/no/nav/soknad/arkivering/soknadsmottaker/service/Converter.kt
> +		"ORIGINAL"
Alle filer av application/pdf kan settes til ARKIV, Alle filer av application/pdf-fullversjon settes til FULLVERSJON. Tror kanskje at alle andre filer, innkludert  application/xml og application/json settes til ORIGINAL. Det åpner for at vi en gang i framtiden kan sende inn original versjon av filer vi har konvertert til PDF.

2022-02-14 13:09 UTC, sjoblomjsqueed commented
> Sjekk kommentar relatert til setting av arkivfomat. Har editert soknadsmottaker-api.yml i innsending-api for generering av HealthAPI, burde du ikke ha lagt til generering av apiet for ping/isAlive/isReady?

Ja, det kan vare lurt at legge til i API:et. Jeg kan se på det og opprette en ny PR.

2022-02-14 13:12 UTC, sjoblomjsqueed commented on mottaker/src/main/kotlin/no/nav/soknad/arkivering/soknadsmottaker/service/Converter.kt
> +		"ORIGINAL"
Er det dette du ser for deg?

2022-02-14 15:55 UTC, sjoblomjsqueed commented on mottaker/src/main/kotlin/no/nav/soknad/arkivering/soknadsmottaker/service/Converter.kt
> +		"ORIGINAL"
> ja

Oppdatert PR

2022-02-15 09:35 UTC, merged